// Package classes implements the tier-0 diff-class detectors from spec §4.
// Every detector is conservative: a class is assigned only on positive
// proof; anything unrecognized is source (full review).
package classes

import (
	"bufio"
	"bytes"
	"path"
	"strings"

	"github.com/bmatcuk/doublestar/v4"

	"github.com/phatblat/agentic-review/internal/classes/manifest"
	"github.com/phatblat/agentic-review/internal/gh"
	"github.com/phatblat/agentic-review/internal/gitattributes"
	"github.com/phatblat/agentic-review/internal/logx"
)

// Class is one diff-class enum value.
type Class string

const (
	ClassSource       Class = "source"
	ClassTest         Class = "test"
	ClassDocs         Class = "docs"
	ClassDeps         Class = "deps"
	ClassGenerated    Class = "generated"
	ClassCIConfig     Class = "ci-config"
	ClassReviewConfig Class = "review-config"
)

// Input is the per-file evidence Classify needs. Content readers are lazy
// (ContentStore-backed) so a file whose class is decided by path alone
// never triggers a network read.
type Input struct {
	File         gh.File
	HeadContent  func() ([]byte, error) // lazy; ContentStore-backed
	BaseContent  func() ([]byte, error)
	Attributes   *gitattributes.Set // parsed .gitattributes at head, nil if absent
	DocsGlobs    []string           // from config
	WorkflowPath string             // the workflow file invoking the action
}

var lockfiles = map[string]bool{
	"Cargo.lock": true, "package-lock.json": true, "pnpm-lock.yaml": true,
	"yarn.lock": true, "bun.lockb": true, "bun.lock": true, "deno.lock": true,
	"go.sum": true, "Gemfile.lock": true, "poetry.lock": true, "uv.lock": true,
}

var ciConfigGlobs = []string{
	".circleci/**", ".gitlab-ci.yml", "azure-pipelines.yml", "Jenkinsfile", ".github/actions/**",
}

var generatedGlobs = []string{"*.pb.go", "*_pb2.py", "*.g.dart", "dist/**", "**/generated/**"}

// DefaultDocsGlobs is the docs glob set used when a repo doesn't configure
// its own (config.Defaults mirrors this exact list).
var DefaultDocsGlobs = []string{"**/*.md", "docs/**", "**/*.rst", "LICENSE*"}

var testGlobs = []string{
	"**/*_test.go", "**/test/**", "**/tests/**", "**/*.test.ts", "**/*.test.js",
	"**/*.spec.ts", "**/*.spec.js", "**/*_test.py", "**/test_*.py", "**/*Test.java",
	"**/*Tests.cs", "**/spec/**",
}

// Classify returns the class of a single file plus a human reason for
// roster.json. Order of evaluation, first match wins: review-config →
// ci-config → deps → generated → docs → test → source.
func Classify(in Input) (Class, string) {
	p := in.File.Path

	if matchAny(p, ".github/agentic-review/**") || (in.WorkflowPath != "" && p == in.WorkflowPath) {
		return ClassReviewConfig, "under .github/agentic-review/ or is the invoking workflow file"
	}

	if matchAny(p, ".github/workflows/**") || matchAny(p, ciConfigGlobs...) {
		return ClassCIConfig, "matches a CI config path"
	}

	if cls, reason, ok := classifyDeps(in); ok {
		return cls, reason
	}

	if cls, reason, ok := classifyGenerated(in); ok {
		return cls, reason
	}

	if matchAny(p, docsGlobsOrDefault(in.DocsGlobs)...) {
		return ClassDocs, "matches the docs glob set"
	}

	if matchAny(p, testGlobs...) {
		return ClassTest, "matches a conventional test glob"
	}

	return ClassSource, ""
}

func classifyDeps(in Input) (Class, string, bool) {
	p := in.File.Path
	if lockfiles[path.Base(p)] {
		return ClassDeps, "known lockfile", true
	}
	parser := manifest.For(p)
	if parser == nil || in.BaseContent == nil || in.HeadContent == nil {
		return "", "", false
	}
	base, err := in.BaseContent()
	if err != nil {
		return "", "", false
	}
	head, err := in.HeadContent()
	if err != nil {
		return "", "", false
	}
	ok, _, err := parser.VersionOnly(base, head)
	if err != nil || !ok {
		return "", "", false
	}
	return ClassDeps, "manifest structural diff is version-only", true
}

func classifyGenerated(in Input) (Class, string, bool) {
	p := in.File.Path
	if in.Attributes != nil {
		if v, ok := in.Attributes.Generated(p); ok {
			if v {
				return ClassGenerated, "gitattributes linguist-generated", true
			}
			// Authoritatively not generated: skip the heuristic and default
			// globs below for this path.
			return "", "", false
		}
	}
	if in.HeadContent != nil {
		if head, err := in.HeadContent(); err == nil {
			if marker, ok := generatedMarker(head); ok {
				logx.Debug("classes: %s marked generated by heuristic (%s)", p, marker)
				return ClassGenerated, "generated marker (" + marker + ") in first 20 lines", true
			}
		}
	}
	if matchAny(p, generatedGlobs...) {
		return ClassGenerated, "matches a default generated-file glob", true
	}
	return "", "", false
}

func generatedMarker(head []byte) (string, bool) {
	sc := bufio.NewScanner(bytes.NewReader(head))
	for range 20 {
		if !sc.Scan() {
			break
		}
		line := sc.Text()
		if strings.Contains(line, "DO NOT EDIT") {
			return "DO NOT EDIT", true
		}
		if strings.Contains(line, "@generated") {
			return "@generated", true
		}
	}
	return "", false
}

func docsGlobsOrDefault(globs []string) []string {
	if len(globs) == 0 {
		return DefaultDocsGlobs
	}
	return globs
}

func matchAny(p string, globs ...string) bool {
	for _, g := range globs {
		if ok, _ := doublestar.Match(g, p); ok {
			return true
		}
	}
	return false
}
