package classes

import (
	"errors"
	"testing"

	"github.com/phatblat/agentic-review/internal/gh"
	"github.com/phatblat/agentic-review/internal/gitattributes"
)

func content(s string) func() ([]byte, error) {
	return func() ([]byte, error) { return []byte(s), nil }
}

func errContent() func() ([]byte, error) {
	return func() ([]byte, error) { return nil, errors.New("not found") }
}

func TestClassifyReviewConfig(t *testing.T) {
	in := Input{File: gh.File{Path: ".github/agentic-review/config.yaml"}}
	if cls, _ := Classify(in); cls != ClassReviewConfig {
		t.Errorf("class = %s, want review-config", cls)
	}
	in2 := Input{File: gh.File{Path: ".github/workflows/review.yml"}, WorkflowPath: ".github/workflows/review.yml"}
	if cls, _ := Classify(in2); cls != ClassReviewConfig {
		t.Errorf("class = %s, want review-config for the invoking workflow file", cls)
	}
}

func TestClassifyCIConfig(t *testing.T) {
	for _, p := range []string{".github/workflows/ci.yml", ".circleci/config.yml", "Jenkinsfile"} {
		if cls, _ := Classify(Input{File: gh.File{Path: p}}); cls != ClassCIConfig {
			t.Errorf("Classify(%q) = %s, want ci-config", p, cls)
		}
	}
}

func TestClassifyDepsLockfile(t *testing.T) {
	if cls, _ := Classify(Input{File: gh.File{Path: "Cargo.lock"}}); cls != ClassDeps {
		t.Errorf("class = %s, want deps for a lockfile", cls)
	}
}

func TestClassifyDepsVersionOnlyManifest(t *testing.T) {
	in := Input{
		File: gh.File{Path: "Cargo.toml"},
		BaseContent: content(`[dependencies]
openssl = "1.0.2"
`),
		HeadContent: content(`[dependencies]
openssl = "3.2.1"
`),
	}
	if cls, _ := Classify(in); cls != ClassDeps {
		t.Errorf("class = %s, want deps for a version-only Cargo.toml change", cls)
	}
}

func TestClassifyNewDependencyIsSource(t *testing.T) {
	in := Input{
		File: gh.File{Path: "Cargo.toml"},
		BaseContent: content(`[dependencies]
openssl = "1.0.2"
`),
		HeadContent: content(`[dependencies]
openssl = "1.0.2"
serde = "1"
`),
	}
	if cls, _ := Classify(in); cls != ClassSource {
		t.Errorf("class = %s, want source for a new dependency", cls)
	}
}

func TestClassifyDepsUnreadableContentFallsThroughToSource(t *testing.T) {
	in := Input{
		File:        gh.File{Path: "Cargo.toml"},
		BaseContent: errContent(),
		HeadContent: content("[dependencies]\n"),
	}
	if cls, _ := Classify(in); cls != ClassSource {
		t.Errorf("class = %s, want source when base content is unreadable", cls)
	}
}

func TestClassifyGeneratedByGitattributes(t *testing.T) {
	attrs := gitattributes.Parse([]byte("*.pb.go linguist-generated\n"))
	in := Input{File: gh.File{Path: "api/service.pb.go"}, Attributes: attrs}
	if cls, _ := Classify(in); cls != ClassGenerated {
		t.Errorf("class = %s, want generated", cls)
	}
}

func TestClassifyGitattributesFalseSuppressesHeuristic(t *testing.T) {
	attrs := gitattributes.Parse([]byte("special.go -linguist-generated\n"))
	in := Input{
		File:        gh.File{Path: "special.go"},
		Attributes:  attrs,
		HeadContent: content("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\n"),
	}
	if cls, _ := Classify(in); cls != ClassSource {
		t.Errorf("class = %s, want source: explicit gitattributes false must suppress the marker heuristic", cls)
	}
}

func TestClassifyGeneratedByMarker(t *testing.T) {
	in := Input{
		File:        gh.File{Path: "internal/api/service.go"},
		HeadContent: content("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n"),
	}
	if cls, _ := Classify(in); cls != ClassGenerated {
		t.Errorf("class = %s, want generated via marker heuristic", cls)
	}
}

func TestClassifyGeneratedByDefaultGlob(t *testing.T) {
	if cls, _ := Classify(Input{File: gh.File{Path: "dist/bundle.js"}}); cls != ClassGenerated {
		t.Errorf("class = %s, want generated via default glob", cls)
	}
}

func TestClassifyDocs(t *testing.T) {
	if cls, _ := Classify(Input{File: gh.File{Path: "docs/guide.md"}}); cls != ClassDocs {
		t.Errorf("class = %s, want docs", cls)
	}
	if cls, _ := Classify(Input{File: gh.File{Path: "LICENSE"}}); cls != ClassDocs {
		t.Errorf("class = %s, want docs for LICENSE", cls)
	}
}

func TestClassifyDocsGlobsOverride(t *testing.T) {
	in := Input{File: gh.File{Path: "notes/README.txt"}, DocsGlobs: []string{"notes/**"}}
	if cls, _ := Classify(in); cls != ClassDocs {
		t.Errorf("class = %s, want docs via repo-configured glob", cls)
	}
}

func TestClassifyTest(t *testing.T) {
	if cls, _ := Classify(Input{File: gh.File{Path: "internal/foo/bar_test.go"}}); cls != ClassTest {
		t.Errorf("class = %s, want test", cls)
	}
}

func TestClassifySourceFallback(t *testing.T) {
	if cls, _ := Classify(Input{File: gh.File{Path: "internal/foo/bar.go"}}); cls != ClassSource {
		t.Errorf("class = %s, want source", cls)
	}
}

func TestClassifyOrderReviewConfigBeatsCIConfig(t *testing.T) {
	// A path under .github/agentic-review/ that is ALSO the invoking
	// workflow path would be ambiguous only if it matched workflows/**;
	// here we assert review-config wins over the generic ci-config match
	// when both .github/agentic-review and .github/workflows could apply
	// to a config-guard-adjacent path.
	in := Input{File: gh.File{Path: ".github/agentic-review/config.yaml"}, WorkflowPath: ".github/workflows/review.yml"}
	if cls, _ := Classify(in); cls != ClassReviewConfig {
		t.Errorf("class = %s, want review-config to take priority", cls)
	}
}
